/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/bootstrap": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Initial data load */
    get: operations["getBootstrap"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/conversations/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get conversation with details */
    get: operations["getConversation"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Character: {
      id: number;
      name: string;
      description?: string;
      personality?: string;
      scenario?: string;
      first_mes?: string;
      mes_example?: string;
    };
    Preset: {
      id: number;
      name: string;
      model: string;
      /** Format: double */
      temperature?: number;
      max_tokens?: number;
      system_prompt?: string;
    };
    Message: {
      id: number;
      conversation_id?: number;
      /** @enum {string} */
      role: "user" | "assistant" | "system";
      content: string;
      parent_id?: number | null;
      active_child_id?: number | null;
      created_at?: string;
    };
    ConversationDetail: {
      id: number;
      character_id?: number;
      preset_id?: number;
      created_at?: string;
      character: components["schemas"]["Character"];
      preset: components["schemas"]["Preset"];
      messages: components["schemas"]["Message"][];
    };
    BootstrapResponse: {
      characters?: components["schemas"]["Character"][];
      presets?: components["schemas"]["Preset"][];
      seeded_conversation?: components["schemas"]["ConversationDetail"];
    };
    GetConversationResponse: {
      conversation?: components["schemas"]["ConversationDetail"];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getBootstrap: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Characters, presets, and optional seeded conversation */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BootstrapResponse"];
        };
      };
    };
  };
  getConversation: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Conversation with character, preset, and messages */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["GetConversationResponse"];
        };
      };
      /** @description Conversation not found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
