// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MessageRole.
const (
	MessageRoleAssistant MessageRole = "assistant"
	MessageRoleSystem    MessageRole = "system"
	MessageRoleUser      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case MessageRoleAssistant:
		return true
	case MessageRoleSystem:
		return true
	case MessageRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for UpdateUserRequestRole.
const (
	UpdateUserRequestRoleAdmin UpdateUserRequestRole = "admin"
	UpdateUserRequestRoleUser  UpdateUserRequestRole = "user"
)

// Valid indicates whether the value is a known member of the UpdateUserRequestRole enum.
func (e UpdateUserRequestRole) Valid() bool {
	switch e {
	case UpdateUserRequestRoleAdmin:
		return true
	case UpdateUserRequestRoleUser:
		return true
	default:
		return false
	}
}

// Defines values for UserRole.
const (
	UserRoleAdmin UserRole = "admin"
	UserRoleUser  UserRole = "user"
)

// Valid indicates whether the value is a known member of the UserRole enum.
func (e UserRole) Valid() bool {
	switch e {
	case UserRoleAdmin:
		return true
	case UserRoleUser:
		return true
	default:
		return false
	}
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	Characters         []Character         `json:"characters"`
	Presets            []Preset            `json:"presets"`
	SeededConversation *ConversationDetail `json:"seeded_conversation,omitempty"`
}

// Character defines model for Character.
type Character struct {
	Description string `json:"description"`
	FirstMes    string `json:"first_mes"`
	Id          int    `json:"id"`
	MesExample  string `json:"mes_example"`
	Name        string `json:"name"`
	Personality string `json:"personality"`
	Scenario    string `json:"scenario"`
}

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	Character   Character `json:"character"`
	CharacterId int       `json:"character_id"`
	CreatedAt   string    `json:"created_at"`
	Id          int       `json:"id"`
	Messages    []Message `json:"messages"`
	Preset      Preset    `json:"preset"`
	PresetId    int       `json:"preset_id"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	CharacterId int `json:"character_id"`
	PresetId    int `json:"preset_id"`
}

// GetConversationResponse defines model for GetConversationResponse.
type GetConversationResponse struct {
	Conversation ConversationDetail `json:"conversation"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Password string `json:"password"`
	Username string `json:"username"`
}

// Message defines model for Message.
type Message struct {
	ActiveChildId  *int        `json:"active_child_id,omitempty"`
	Content        string      `json:"content"`
	ConversationId int         `json:"conversation_id"`
	CreatedAt      string      `json:"created_at"`
	Id             int         `json:"id"`
	ParentId       *int        `json:"parent_id,omitempty"`
	Role           MessageRole `json:"role"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// Preset defines model for Preset.
type Preset struct {
	Id           int     `json:"id"`
	MaxTokens    int     `json:"max_tokens"`
	Model        string  `json:"model"`
	Name         string  `json:"name"`
	SystemPrompt string  `json:"system_prompt"`
	Temperature  float64 `json:"temperature"`
}

// PromptMessage defines model for PromptMessage.
type PromptMessage struct {
	Content string `json:"content"`
	Role    string `json:"role"`
}

// PromptResponse defines model for PromptResponse.
type PromptResponse struct {
	Messages []PromptMessage `json:"messages"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName *string `json:"display_name,omitempty"`
	Password    string  `json:"password"`
	Username    string  `json:"username"`
}

// ServerSettings defines model for ServerSettings.
type ServerSettings struct {
	AllowRegistration *bool `json:"allow_registration,omitempty"`
}

// UpdateUserRequest defines model for UpdateUserRequest.
type UpdateUserRequest struct {
	Role *UpdateUserRequestRole `json:"role,omitempty"`
}

// UpdateUserRequestRole defines model for UpdateUserRequest.Role.
type UpdateUserRequestRole string

// User defines model for User.
type User struct {
	CreatedAt   string   `json:"created_at"`
	DisplayName string   `json:"display_name"`
	Id          string   `json:"id"`
	Role        UserRole `json:"role"`
	Username    string   `json:"username"`
}

// UserRole defines model for User.Role.
type UserRole string

// UserList defines model for UserList.
type UserList struct {
	Users []User `json:"users"`
}

// UpdateSettingsJSONRequestBody defines body for UpdateSettings for application/json ContentType.
type UpdateSettingsJSONRequestBody = ServerSettings

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UpdateUserRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// RegisterJSONRequestBody defines body for Register for application/json ContentType.
type RegisterJSONRequestBody = RegisterRequest

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get server settings (admin only)
	// (GET /api/admin/settings)
	GetSettings(w http.ResponseWriter, r *http.Request)
	// Update server settings (admin only)
	// (PATCH /api/admin/settings)
	UpdateSettings(w http.ResponseWriter, r *http.Request)
	// List all users (admin only)
	// (GET /api/admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// Update a user (admin only)
	// (PATCH /api/admin/users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id string)
	// Log in
	// (POST /api/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Log out (destroy session)
	// (POST /api/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)
	// Get current user
	// (GET /api/auth/me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// Register a new user
	// (POST /api/auth/register)
	Register(w http.ResponseWriter, r *http.Request)
	// Initial data load
	// (GET /api/bootstrap)
	GetBootstrap(w http.ResponseWriter, r *http.Request)
	// Create a new conversation
	// (POST /api/conversations)
	CreateConversation(w http.ResponseWriter, r *http.Request)
	// Get conversation with details
	// (GET /api/conversations/{id})
	GetConversation(w http.ResponseWriter, r *http.Request, id int)
	// Get constructed prompt for a conversation
	// (GET /api/conversations/{id}/prompt)
	GetConversationPrompt(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Get server settings (admin only)
// (GET /api/admin/settings)
func (_ Unimplemented) GetSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update server settings (admin only)
// (PATCH /api/admin/settings)
func (_ Unimplemented) UpdateSettings(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List all users (admin only)
// (GET /api/admin/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a user (admin only)
// (PATCH /api/admin/users/{id})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log in
// (POST /api/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Log out (destroy session)
// (POST /api/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get current user
// (GET /api/auth/me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Register a new user
// (POST /api/auth/register)
func (_ Unimplemented) Register(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Initial data load
// (GET /api/bootstrap)
func (_ Unimplemented) GetBootstrap(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new conversation
// (POST /api/conversations)
func (_ Unimplemented) CreateConversation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get conversation with details
// (GET /api/conversations/{id})
func (_ Unimplemented) GetConversation(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get constructed prompt for a conversation
// (GET /api/conversations/{id}/prompt)
func (_ Unimplemented) GetConversationPrompt(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetSettings operation middleware
func (siw *ServerInterfaceWrapper) GetSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateSettings operation middleware
func (siw *ServerInterfaceWrapper) UpdateSettings(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateSettings(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Register operation middleware
func (siw *ServerInterfaceWrapper) Register(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Register(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateConversation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConversation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversationPrompt operation middleware
func (siw *ServerInterfaceWrapper) GetConversationPrompt(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversationPrompt(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/settings", wrapper.GetSettings)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/admin/settings", wrapper.UpdateSettings)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/admin/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/admin/users/{id}", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/auth/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/auth/register", wrapper.Register)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/bootstrap", wrapper.GetBootstrap)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/conversations", wrapper.CreateConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/conversations/{id}", wrapper.GetConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/conversations/{id}/prompt", wrapper.GetConversationPrompt)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RZb2/bthP+KgR/vxcdINhpEwyDgb1ou3UIkG5BsuxNWxi0eLHZSaRKnpIYgb/7QFKy",
	"RYlU7C1ut3eJeTzePc/dwz96pLkqKyVBoqGzR2ryFZTM/flGKTSoWXUFplLSgP2x0qoCjQKcSb5imuUI",
	"2v0nEEr3x/813NIZ/d9053vaOJ6+bafQTUZxXQGdUaY1W9v/Kw0GcH9nl84+5skAcODzXMk70IahUPLJ",
	"yDq2PwEyUdDNJqMavtRCA6ezD918d8F+2q6uFp8hd+HsshxgxsHkWlRtRM1Ug1rIpZ16K7TBeemNB6OC",
	"d34WEmHpkSzBzOGBlVUB0XmSlfGBCrRRkhUC19Fxk4NkWqjIYA8cwWmzThYkGa7R8djNNcwgCumQnnQ9",
	"HlSF21nzFLq5BobA5wwPJcWwJexfz+/9hHRr7N8Q3j6RUYy5AIXu/CD9jt3WiHYyjTLnpnf5u4IvNRgc",
	"ITBJxSF5JVOKRfkLYBhiUvSeWVO67mKBXailSCNWMWPulebRwqwN6ETn96LYWmY7j7Fg2godxMFyFHcw",
	"z1ei4A07si4KtrCChLqGLNZXSiLIeFN1cXnuxqyYBol7h6mVV1WQddmCRTPKjBEGmbQNYNYGoexANiaS",
	"/dSaFXZ4BInFaLjcqkHIQlKJ2MMc1Z8gTWJccSgO2zh8xvNKq7KKo49QVqAZ1tp5uFW6tDxRruqFS7eZ",
	"IetykVKlpiZ9fKHLIKt+PHHQ7FCygseKsa2AcXJ7LKZjSIvLwVtGmNRg4+hFOKrTV7AUBkEntYYLUxVs",
	"PW9romQPFyCXuKKz78+yyNmio02lkK3tD9m4UnXcnr7KujNfZc8kY9eg70BfA6KQSxNRs6JQ93PtANGs",
	"d1ZbKFUAk27xgeebijOEGzMCY19OGC+FPSY5WYkqyHAVEztaPqGGffrG5XJY/HvGe8i243q8Q1oQ4k4W",
	"x8XQgnEhYkhbz/u3kgP1qQ7yLodhWDshb9XgiE+vr38mIHmlhERy+dv172TKKjHtbgJm+ij4ZmpAciIM",
	"kQqJUzzgZAUaJh/lOdoB3XQocFIyWbOiWBMlCa6A5CtBtKoR9OSjJQcFWtboO7aAgry+PKcZtev5mE4m",
	"J5OXNldVgWSVoDN6OjmZnLq+wZWDykXpuJ6aTqMs/b6jnA4LJc85ndnD07aZLF5e3pz9q5OTnrqyqipE",
	"7iZPPxvfWp6Dpxjqta0DvQe2syDbgDcZPTs5HZLyq0Li69j6MHVZMr32iRAT+iAvnCFRslh/52UN89UQ",
	"A9/5AQxOAN4ovj4qArvytAeYzTfF34PA/z4B3sETHGyybnVuuzxamlYZboy/sh8NmK0ERSB5XRTEh3go",
	"FtYjYe30pzFwKuIvBSMVeuNPrxXTrAT/dvPhkQobiO399tA18+IcFlfWwaOv7J+OU/HDDfUrF73fFtKl",
	"XjfbxplfMzT6gxWCu1UJaK30PjVgLc6GFjYOtzXcqlryeNswF02qUmpcTQt7m3Q1okysW9zwcZgMLrL/",
	"EhIv1HIJnLSwvxzCfi7vLIck18BBomCF6bepWpKmdwOcVY2jQNvxQcoR4psYrflwYVUjecHBoFZrYsDY",
	"Db7PuT+JpTbu90C/AfBva23v4L5e3cEpRYDrjBpXFvzcdlxky8473nrJt2emLhXhAu+ENtg9W7mYFpCr",
	"Eoxvygm5rhfGlq5sLT2I5qNsipgM7ww/2qomQvZ3M39CC4loL19H6r3+3W6v9nt5fA21SDfHe8IkJ0XY",
	"j/9EUa86TNjDMxeGLYpB+bTIEEYk3PcqaNF+AxlroO2HkmP20fBrTKyptt8nMtJ8nsgcrMpZsIL47yIk",
	"eHQM8TiXwooc4QwZKRTjOzSCK0ta2obvvUcq6vTD8lcu79TbcYyipti7WJJ7gSvC3ftwf3Px9k1xDmhL",
	"3CTHqrXHy3MdA3dv8J+O2AWHAD0AePs5oG0O3xvbN7HUwSvwlDqAuV1olNPUrX/3groPZf697z9HXO/d",
	"M86XQV3ntjk8JM/LTN/5rbKS3+uozeavAAAA//+JJIYxER8AAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
