// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	Characters         *[]Character        `json:"characters,omitempty"`
	Presets            *[]Preset           `json:"presets,omitempty"`
	SeededConversation *ConversationDetail `json:"seeded_conversation,omitempty"`
}

// Character defines model for Character.
type Character struct {
	Description *string `json:"description,omitempty"`
	FirstMes    *string `json:"first_mes,omitempty"`
	Id          int     `json:"id"`
	MesExample  *string `json:"mes_example,omitempty"`
	Name        string  `json:"name"`
	Personality *string `json:"personality,omitempty"`
	Scenario    *string `json:"scenario,omitempty"`
}

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	Character   Character `json:"character"`
	CharacterId *int      `json:"character_id,omitempty"`
	CreatedAt   *string   `json:"created_at,omitempty"`
	Id          int       `json:"id"`
	Messages    []Message `json:"messages"`
	Preset      Preset    `json:"preset"`
	PresetId    *int      `json:"preset_id,omitempty"`
}

// GetConversationResponse defines model for GetConversationResponse.
type GetConversationResponse struct {
	Conversation *ConversationDetail `json:"conversation,omitempty"`
}

// Message defines model for Message.
type Message struct {
	ActiveChildId  *int        `json:"active_child_id,omitempty"`
	Content        string      `json:"content"`
	ConversationId *int        `json:"conversation_id,omitempty"`
	CreatedAt      *string     `json:"created_at,omitempty"`
	Id             int         `json:"id"`
	ParentId       *int        `json:"parent_id,omitempty"`
	Role           MessageRole `json:"role"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// Preset defines model for Preset.
type Preset struct {
	Id           int      `json:"id"`
	MaxTokens    *int     `json:"max_tokens,omitempty"`
	Model        string   `json:"model"`
	Name         string   `json:"name"`
	SystemPrompt *string  `json:"system_prompt,omitempty"`
	Temperature  *float64 `json:"temperature,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Initial data load
	// (GET /api/bootstrap)
	GetBootstrap(w http.ResponseWriter, r *http.Request)
	// Get conversation with details
	// (GET /api/conversations/{id})
	GetConversation(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Initial data load
// (GET /api/bootstrap)
func (_ Unimplemented) GetBootstrap(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get conversation with details
// (GET /api/conversations/{id})
func (_ Unimplemented) GetConversation(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/bootstrap", wrapper.GetBootstrap)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/conversations/{id}", wrapper.GetConversation)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7RWSW/bPBD9KwK/72jYbpOTbl3QIIcCQa9BIIzFsc1UXMoZpTEM//eCpDZXUuIAzU0S",
	"Odt7b2Z0FKXVzho0TCI/Cir3qCE+fraWiT24H0jOGsLw0Xnr0LPCeKXcg4eS0cc3xajjw/8etyIX/616",
	"36vG8epLayJOC8EHhyIX4D0cwrvzSMiXO7uL96c8EaJEWZTWPKEnYGXNq5kN7n5FBlWJU+/Zbh6xjKH6",
	"CkZ4SKTSK9dGa0yJvTK7YLpVnrjQ6fLoVMnBZ2UYdwkljVTgM2hX4aSdAT194NCTNVApPkyeU4kGvLIT",
	"h6eF8PirVh6lyO9Dak2chylExsjNS+VNAumsijlwSo/AKAvgt2JKsMPLpfY9Gcyr9nKtpvszFU0B32PX",
	"BRtUMMXIDfKQlBc6+B0apIVqFAxKVk9YlHtVyaZ8U1cVbIKw2de4mCLYGkYzze4w+3+tEAceDV+cprep",
	"O9HUOhBXU6QLiBQxmMAYHYhRD/h6qdmiv776KZLvOt2dwzyreXgu2P5EQzPnVmL1tgmTSiqct9pNw8uo",
	"HXrg2kcPW+t1IEJIW29ihY2FqfVmTv8xfJvfGIlgo8w2jTHFgQfxDTZYZZ/ubsVCBIlEeYv1cr38ELKy",
	"Dg04JXJxtVwvr0JfAe8jLitwarVpd1/4sksg21iHsuZWijx0WLcgA11Nh0UXH9frprda5YJzlSqj9eqR",
	"Uqultnqt6cZbONZ7tmn6lUSLrNmhiwyMzGy8AVWW9mF21u7BD9Vagz+IXNwaxQqqTAJDVlmQ8TyiMbSi",
	"1VHJ00uwDMdEBNaDxvSPcH8UKuQbwG55zRu9d6SnDuvRGU3Ih3eEe25wToE+uJf9VrzPujndspBI6Cb1",
	"aSGu19ejH4VzT8ZytrW1kX/xc4N8Rl8KKeMcppDf6U8AAAD//4Ltv07MCQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
