// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for MessageRole.
const (
	Assistant MessageRole = "assistant"
	System    MessageRole = "system"
	User      MessageRole = "user"
)

// Valid indicates whether the value is a known member of the MessageRole enum.
func (e MessageRole) Valid() bool {
	switch e {
	case Assistant:
		return true
	case System:
		return true
	case User:
		return true
	default:
		return false
	}
}

// BootstrapResponse defines model for BootstrapResponse.
type BootstrapResponse struct {
	Characters         []Character         `json:"characters"`
	Presets            []Preset            `json:"presets"`
	SeededConversation *ConversationDetail `json:"seeded_conversation,omitempty"`
}

// Character defines model for Character.
type Character struct {
	Description string `json:"description"`
	FirstMes    string `json:"first_mes"`
	Id          int    `json:"id"`
	MesExample  string `json:"mes_example"`
	Name        string `json:"name"`
	Personality string `json:"personality"`
	Scenario    string `json:"scenario"`
}

// ConversationDetail defines model for ConversationDetail.
type ConversationDetail struct {
	Character   Character `json:"character"`
	CharacterId int       `json:"character_id"`
	CreatedAt   string    `json:"created_at"`
	Id          int       `json:"id"`
	Messages    []Message `json:"messages"`
	Preset      Preset    `json:"preset"`
	PresetId    int       `json:"preset_id"`
}

// CreateConversationRequest defines model for CreateConversationRequest.
type CreateConversationRequest struct {
	CharacterId int `json:"character_id"`
	PresetId    int `json:"preset_id"`
}

// GetConversationResponse defines model for GetConversationResponse.
type GetConversationResponse struct {
	Conversation ConversationDetail `json:"conversation"`
}

// Message defines model for Message.
type Message struct {
	ActiveChildId  *int        `json:"active_child_id,omitempty"`
	Content        string      `json:"content"`
	ConversationId int         `json:"conversation_id"`
	CreatedAt      string      `json:"created_at"`
	Id             int         `json:"id"`
	ParentId       *int        `json:"parent_id,omitempty"`
	Role           MessageRole `json:"role"`
}

// MessageRole defines model for Message.Role.
type MessageRole string

// Preset defines model for Preset.
type Preset struct {
	Id           int     `json:"id"`
	MaxTokens    int     `json:"max_tokens"`
	Model        string  `json:"model"`
	Name         string  `json:"name"`
	SystemPrompt string  `json:"system_prompt"`
	Temperature  float64 `json:"temperature"`
}

// PromptMessage defines model for PromptMessage.
type PromptMessage struct {
	Content string `json:"content"`
	Role    string `json:"role"`
}

// PromptResponse defines model for PromptResponse.
type PromptResponse struct {
	Messages []PromptMessage `json:"messages"`
}

// CreateConversationJSONRequestBody defines body for CreateConversation for application/json ContentType.
type CreateConversationJSONRequestBody = CreateConversationRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Initial data load
	// (GET /api/bootstrap)
	GetBootstrap(w http.ResponseWriter, r *http.Request)
	// Create a new conversation
	// (POST /api/conversations)
	CreateConversation(w http.ResponseWriter, r *http.Request)
	// Get conversation with details
	// (GET /api/conversations/{id})
	GetConversation(w http.ResponseWriter, r *http.Request, id int)
	// Get constructed prompt for a conversation
	// (GET /api/conversations/{id}/prompt)
	GetConversationPrompt(w http.ResponseWriter, r *http.Request, id int)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Initial data load
// (GET /api/bootstrap)
func (_ Unimplemented) GetBootstrap(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create a new conversation
// (POST /api/conversations)
func (_ Unimplemented) CreateConversation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get conversation with details
// (GET /api/conversations/{id})
func (_ Unimplemented) GetConversation(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get constructed prompt for a conversation
// (GET /api/conversations/{id}/prompt)
func (_ Unimplemented) GetConversationPrompt(w http.ResponseWriter, r *http.Request, id int) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetBootstrap operation middleware
func (siw *ServerInterfaceWrapper) GetBootstrap(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBootstrap(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateConversation operation middleware
func (siw *ServerInterfaceWrapper) CreateConversation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateConversation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversation operation middleware
func (siw *ServerInterfaceWrapper) GetConversation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversation(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetConversationPrompt operation middleware
func (siw *ServerInterfaceWrapper) GetConversationPrompt(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "id" -------------
	var id int

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetConversationPrompt(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/bootstrap", wrapper.GetBootstrap)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/conversations", wrapper.CreateConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/conversations/{id}", wrapper.GetConversation)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/conversations/{id}/prompt", wrapper.GetConversationPrompt)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXTY8bNwz9K4Lao2E7TU6+Nf0I9lB0ke0tCQx6RNtKZyRF5CQxFvPfC0ljez40Xhtw",
	"D7mtRyRFvkc+cZ9lYStnDRomuXqWVOyxgvjnW2uZ2IN7j+SsIQwfnbcOPWuMJsUePBSMPv7SjFX842eP",
	"W7mSPy3OsRdt4MVvRxfZzCQfHMqVBO/hEH47j4R8fbDHaJ+LRIgK1bqw5it6AtbWvJhZx/Z3ZNClbJqZ",
	"9Pil1h6VXH3o1ntO9tPpdrv5jEVM51zlCDOFVHjtjhm1rsRem11w3WpPvK6S8ehUq85nbRh3CckKaY3f",
	"oXIlZv0MVPkDh56sgVLzIXtOBRrw2mYOB+BoJdt7Zr0i+3d0InZr7VeQhXRMz3Q/3tSFJ6/1FLqFR2BU",
	"a+BbSSHY4fX9/FdymB6N6wci2U9UlGOuh0LXv1d+x+5kJDuVZpmL7l3+3uOXGokvEDhJxS11TZaUy/Id",
	"cj/FSdG7s6Z0w+USOzbFKBEoWH/FdbHXpWoBMXVZwiZoAPsaZ7lWtobR5Pu4m8q9Z8GBR8NXp+ltEjI0",
	"dRVQqik2HBBpYjCh5+hAjFUHsku6NCytveGMR6+wHA2PpwHsszA5/PB9zfZfNDRxbhWWt2l1qnjtvK1c",
	"Hn3GyqEHrn2MsLW+CjxJZetNLLf1MHW1mRKCVsJTfv2QvaqG+eRBC0eTHXypGY8dcJncAYvTOUzP880q",
	"3S9qpNWDDC9IYzDVZmtHa4F8evpDoFHOasPi8e+nf8QCnF50u5gWz1o1C0KjhCZhLItIGSqxR4/zj+aB",
	"w4HHnSZGj0pUYGooy4OwRvAeRbHXwtua0c8/hneaNQfM5Z+wwVL8+vggZzLcl3JazpfzV6Fc69CA03Il",
	"X8+X89dBWYH3EbaY5ea4OIYvuzQzNvaQtuZByVXQ2tN2GUax5SaG+GW5HLQGOFfqInovPlMS3cTFS0yN",
	"V9iIeR/r0y5AM9HudDMBRgkbLaAUaZkUPaUOcaiuKvAHuZIPRrOGUihgEKUFFc/HnMXus5SBZPxIytRH",
	"SPzWqsPdMJl+jZt+6wZpbkbkvLpbIlMPbo6iJM09BsQ3zXuh4qNKAzqSvQBh8NuYtolRutStA14ceKgw",
	"/d/z4VnqkGOYgaN6rpKS9rGcdXAZLS6f/scpuAXoEcCnHeo4HGk2TqrWzOSb5ZuxgvUiBXHa2tqoAU/v",
	"kF/gdEr2zm/gNZQlxf7hiBu8XHm+iH1dhOFIkNyXmWHwrfUChhPVNP8FAAD//yySI1hGEAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
