// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: characters.sql

package dbq

import (
	"context"
)

const getCharacter = `-- name: GetCharacter :one
SELECT id, name, description, personality, scenario, first_mes, mes_example
FROM characters
WHERE id = ?
`

type GetCharacterRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Personality string `json:"personality"`
	Scenario    string `json:"scenario"`
	FirstMes    string `json:"first_mes"`
	MesExample  string `json:"mes_example"`
}

func (q *Queries) GetCharacter(ctx context.Context, id int64) (GetCharacterRow, error) {
	row := q.db.QueryRowContext(ctx, getCharacter, id)
	var i GetCharacterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Personality,
		&i.Scenario,
		&i.FirstMes,
		&i.MesExample,
	)
	return i, err
}

const listCharacters = `-- name: ListCharacters :many
SELECT id, name, description, personality, scenario, first_mes, mes_example
FROM characters
ORDER BY id
`

type ListCharactersRow struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	Description string `json:"description"`
	Personality string `json:"personality"`
	Scenario    string `json:"scenario"`
	FirstMes    string `json:"first_mes"`
	MesExample  string `json:"mes_example"`
}

func (q *Queries) ListCharacters(ctx context.Context) ([]ListCharactersRow, error) {
	rows, err := q.db.QueryContext(ctx, listCharacters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCharactersRow{}
	for rows.Next() {
		var i ListCharactersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Personality,
			&i.Scenario,
			&i.FirstMes,
			&i.MesExample,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
