// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package dbq

import (
	"context"
)

const createConversation = `-- name: CreateConversation :execlastid
INSERT INTO conversations (character_id, preset_id)
VALUES (?, ?)
`

type CreateConversationParams struct {
	CharacterID int64 `json:"character_id"`
	PresetID    int64 `json:"preset_id"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createConversation, arg.CharacterID, arg.PresetID)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const getConversation = `-- name: GetConversation :one
SELECT id, character_id, preset_id, created_at
FROM conversations
WHERE id = ?
`

func (q *Queries) GetConversation(ctx context.Context, id int64) (Conversation, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.CharacterID,
		&i.PresetID,
		&i.CreatedAt,
	)
	return i, err
}

const getFirstConversationID = `-- name: GetFirstConversationID :one
SELECT id FROM conversations ORDER BY id LIMIT 1
`

func (q *Queries) GetFirstConversationID(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFirstConversationID)
	var id int64
	err := row.Scan(&id)
	return id, err
}
