// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: messages.sql

package dbq

import (
	"context"
	"database/sql"
)

const appendMessage = `-- name: AppendMessage :exec
INSERT INTO messages (conversation_id, role, content, parent_id)
VALUES (?, ?, ?, ?)
`

type AppendMessageParams struct {
	ConversationID int64         `json:"conversation_id"`
	Role           string        `json:"role"`
	Content        string        `json:"content"`
	ParentID       sql.NullInt64 `json:"parent_id"`
}

func (q *Queries) AppendMessage(ctx context.Context, arg AppendMessageParams) error {
	_, err := q.db.ExecContext(ctx, appendMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.ParentID,
	)
	return err
}

const getMessagesByConversation = `-- name: GetMessagesByConversation :many
SELECT id, conversation_id, role, content, parent_id, active_child_id, created_at
FROM messages
WHERE conversation_id = ?
ORDER BY id
`

func (q *Queries) GetMessagesByConversation(ctx context.Context, conversationID int64) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, getMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.ParentID,
			&i.ActiveChildID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
