// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: presets.sql

package dbq

import (
	"context"
)

const getPreset = `-- name: GetPreset :one
SELECT id, name, model, temperature, max_tokens, system_prompt
FROM presets
WHERE id = ?
`

type GetPresetRow struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	Model        string  `json:"model"`
	Temperature  float64 `json:"temperature"`
	MaxTokens    int64   `json:"max_tokens"`
	SystemPrompt string  `json:"system_prompt"`
}

func (q *Queries) GetPreset(ctx context.Context, id int64) (GetPresetRow, error) {
	row := q.db.QueryRowContext(ctx, getPreset, id)
	var i GetPresetRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Model,
		&i.Temperature,
		&i.MaxTokens,
		&i.SystemPrompt,
	)
	return i, err
}

const listPresets = `-- name: ListPresets :many
SELECT id, name, model, temperature, max_tokens, system_prompt
FROM presets
ORDER BY id
`

type ListPresetsRow struct {
	ID           int64   `json:"id"`
	Name         string  `json:"name"`
	Model        string  `json:"model"`
	Temperature  float64 `json:"temperature"`
	MaxTokens    int64   `json:"max_tokens"`
	SystemPrompt string  `json:"system_prompt"`
}

func (q *Queries) ListPresets(ctx context.Context) ([]ListPresetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPresets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPresetsRow{}
	for rows.Next() {
		var i ListPresetsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Model,
			&i.Temperature,
			&i.MaxTokens,
			&i.SystemPrompt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
