// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: resources.sql

package dbq

import (
	"context"
)

const deleteRelation = `-- name: DeleteRelation :exec
DELETE FROM resource_relations WHERE src_id = ? AND dst_id = ? AND relation = ?
`

type DeleteRelationParams struct {
	SrcID    string `json:"src_id"`
	DstID    string `json:"dst_id"`
	Relation string `json:"relation"`
}

func (q *Queries) DeleteRelation(ctx context.Context, arg DeleteRelationParams) error {
	_, err := q.db.ExecContext(ctx, deleteRelation, arg.SrcID, arg.DstID, arg.Relation)
	return err
}

const deleteRelationsByDst = `-- name: DeleteRelationsByDst :exec
DELETE FROM resource_relations WHERE dst_id = ?
`

func (q *Queries) DeleteRelationsByDst(ctx context.Context, dstID string) error {
	_, err := q.db.ExecContext(ctx, deleteRelationsByDst, dstID)
	return err
}

const deleteRelationsBySrc = `-- name: DeleteRelationsBySrc :exec
DELETE FROM resource_relations WHERE src_id = ?
`

func (q *Queries) DeleteRelationsBySrc(ctx context.Context, srcID string) error {
	_, err := q.db.ExecContext(ctx, deleteRelationsBySrc, srcID)
	return err
}

const deleteResource = `-- name: DeleteResource :exec
DELETE FROM resources WHERE id = ?
`

func (q *Queries) DeleteResource(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteResource, id)
	return err
}

const deleteResourcesByKindAndUser = `-- name: DeleteResourcesByKindAndUser :exec
DELETE FROM resources WHERE kind = ? AND user_id = ?
`

type DeleteResourcesByKindAndUserParams struct {
	Kind   string `json:"kind"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeleteResourcesByKindAndUser(ctx context.Context, arg DeleteResourcesByKindAndUserParams) error {
	_, err := q.db.ExecContext(ctx, deleteResourcesByKindAndUser, arg.Kind, arg.UserID)
	return err
}

const getRelationsByDst = `-- name: GetRelationsByDst :many
SELECT src_id, dst_id, relation FROM resource_relations WHERE dst_id = ?
`

func (q *Queries) GetRelationsByDst(ctx context.Context, dstID string) ([]ResourceRelation, error) {
	rows, err := q.db.QueryContext(ctx, getRelationsByDst, dstID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceRelation{}
	for rows.Next() {
		var i ResourceRelation
		if err := rows.Scan(&i.SrcID, &i.DstID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRelationsBySrc = `-- name: GetRelationsBySrc :many
SELECT src_id, dst_id, relation FROM resource_relations WHERE src_id = ?
`

func (q *Queries) GetRelationsBySrc(ctx context.Context, srcID string) ([]ResourceRelation, error) {
	rows, err := q.db.QueryContext(ctx, getRelationsBySrc, srcID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResourceRelation{}
	for rows.Next() {
		var i ResourceRelation
		if err := rows.Scan(&i.SrcID, &i.DstID, &i.Relation); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRelation = `-- name: UpsertRelation :exec
INSERT OR IGNORE INTO resource_relations (src_id, dst_id, relation)
VALUES (?, ?, ?)
`

type UpsertRelationParams struct {
	SrcID    string `json:"src_id"`
	DstID    string `json:"dst_id"`
	Relation string `json:"relation"`
}

func (q *Queries) UpsertRelation(ctx context.Context, arg UpsertRelationParams) error {
	_, err := q.db.ExecContext(ctx, upsertRelation, arg.SrcID, arg.DstID, arg.Relation)
	return err
}

const upsertResource = `-- name: UpsertResource :exec
INSERT INTO resources (id, user_id, kind, title, content, tags, meta, updated_at)
VALUES (?, ?, ?, ?, ?, ?, ?, strftime('%Y-%m-%dT%H:%M:%SZ', 'now'))
ON CONFLICT(id) DO UPDATE SET
    title = excluded.title,
    content = excluded.content,
    tags = excluded.tags,
    meta = excluded.meta,
    updated_at = excluded.updated_at
`

type UpsertResourceParams struct {
	ID      string `json:"id"`
	UserID  string `json:"user_id"`
	Kind    string `json:"kind"`
	Title   string `json:"title"`
	Content string `json:"content"`
	Tags    string `json:"tags"`
	Meta    string `json:"meta"`
}

func (q *Queries) UpsertResource(ctx context.Context, arg UpsertResourceParams) error {
	_, err := q.db.ExecContext(ctx, upsertResource,
		arg.ID,
		arg.UserID,
		arg.Kind,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.Meta,
	)
	return err
}
