// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package dbq

import (
	"context"
)

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expiry < ?
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context, expiry float64) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredSessions, expiry)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token = ?
`

func (q *Queries) DeleteSession(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteSession, token)
	return err
}

const getAllSessions = `-- name: GetAllSessions :many
SELECT token, data FROM sessions WHERE expiry >= ?
`

type GetAllSessionsRow struct {
	Token string `json:"token"`
	Data  []byte `json:"data"`
}

func (q *Queries) GetAllSessions(ctx context.Context, expiry float64) ([]GetAllSessionsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllSessions, expiry)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllSessionsRow{}
	for rows.Next() {
		var i GetAllSessionsRow
		if err := rows.Scan(&i.Token, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSession = `-- name: GetSession :one
SELECT data, expiry FROM sessions WHERE token = ?
`

type GetSessionRow struct {
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

func (q *Queries) GetSession(ctx context.Context, token string) (GetSessionRow, error) {
	row := q.db.QueryRowContext(ctx, getSession, token)
	var i GetSessionRow
	err := row.Scan(&i.Data, &i.Expiry)
	return i, err
}

const upsertSession = `-- name: UpsertSession :exec
INSERT INTO sessions (token, data, expiry) VALUES (?, ?, ?)
ON CONFLICT(token) DO UPDATE SET data = excluded.data, expiry = excluded.expiry
`

type UpsertSessionParams struct {
	Token  string  `json:"token"`
	Data   []byte  `json:"data"`
	Expiry float64 `json:"expiry"`
}

func (q *Queries) UpsertSession(ctx context.Context, arg UpsertSessionParams) error {
	_, err := q.db.ExecContext(ctx, upsertSession, arg.Token, arg.Data, arg.Expiry)
	return err
}
